---
- name: Running show commands on cisco switche
  hosts: all
  gather_facts: false
  connection: network_cli
  
  collections:
    - name: cisco.ios
    - name: ansible.netcommon

  vars:
    network_os: ios
  tasks:
    - name: Run multiple show commands on cisco ios nodes
      cisco.ios.ios_command:
        commands:
          - show version | i Version
      register: print_output

    - debug: var=print_output.stdout_lines
...
