---
- name: Running show commands on cisco switche
  hosts: 172.30.197.177
  gather_facts: false

  tasks:
    - name: Run multiple show commands on cisco ios nodes
      ios_command:
        commands:
          - show version | i Version
      register: print_output

    - debug: var=print_output.stdout_lines
...
